### ISSUE TITLE
IOS 10 : attempts to access privacy-sensitive data

### ISSUE THREAD

**Issue by MrBasque** [alexsorokoletov/Xamarin.Firebase.iOS#2]
After offering our app to the app-store, we received the following errors:

> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data. 
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.
## 

We are not using the Calendar or PhotoLibrary or whatsoever, but this seems to be a known FireBase issue which is fixed since version 7.11.0. 

> Apps no longer need to provide text for NSCalendarsUsageDescription and NSBluetoothPeripheralUsageDescription when updating apps for iOS 10.

(See: https://firebase.google.com/docs/admob/release-notes)

Is there any way those fixes could be incorporated in this repo?

**Comment by alexsorokoletov** [comment]
@MrBasque Sorry for the delay, I am preparing to release fresh libraries soon. The change will be included as well.
I am wondering why did I miss notification for this issue.

**Comment by MrBasque** [comment]
Thanks for your response @alexsorokoletov. for clarity: I received the warnings in a mail from Apple during the appstore-publish-approval-process.

**Comment by alexsorokoletov** [comment]
@MrBasque still working on this

**Comment by alexsorokoletov** [comment]
Closing as Xamarin now provides official Firebase NuGet packages.
