### ISSUE TITLE
Is this firebase phone number authentication available in xamarin? 

### ISSUE THREAD

**Issue by suresh480** [alexsorokoletov/Xamarin.Firebase.iOS#3]
Is this firebase phone number authentication available in xamarin? 
  we are trying to bing phone auth but we stroked at build issue 
Can you please provide phone auth in  xamarin.
Thanks.

**Comment by alexsorokoletov** [comment]
What is the build issue you are facing @suresh480 ?

**Comment by suresh480** [comment]
Thanks for replay. 
I generated firebase auth xamarin binding by  following below link :-https://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/walkthrough/
but while integrating in project we getting error like below 
Error message:-
Could not create an native instance of the type 'FIRPhoneAuthiOS.FIROptions': the native class hasn't been loaded.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.

Please find attached screen shot for your reference.

![screen shot 2017-07-17 at 6 18 16 pm](https://user-images.githubusercontent.com/16954210/28274853-d3d58a2a-6b2f-11e7-9310-e0131b2b1019.png)

**Comment by alexsorokoletov** [comment]
Congratulations on making your own iOS binding for Xamarin!
The error that you see is saying that the native part of your binding is missing.
It was not loaded and C# code that calls it cannot continue execution any more.

Wondering, why are you creating your own binding when you can use this nuget package https://www.nuget.org/packages/Xamarin.Firebase.Auth/42.1024.0-beta1 ?

**Comment by Balakrishna12** [comment]
We creating binding for firebase pone number authentication.
is this latest  Xamarin.Firebase.Auth/42.1024.0-beta1 version firebase phone number authentication available?
we are unable to adding this package to our project, getting below error:-
Could not install package 'Xamarin.Firebase.Auth 42.1021.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by suresh480** [comment]
We creating binding for firebase pone number authentication.
is this latest Xamarin.Firebase.Auth/42.1024.0-beta1 version firebase phone number authentication available?
we are unable to adding this package to our project, getting below error:-
Could not install package 'Xamarin.Firebase.Auth 42.1024.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by alexsorokoletov** [comment]
As the error says, you have to contact package author, that is Xamarin team.
I would strongly suggest to use this package (mentioned above) instead of creating own binding.

**Comment by HemilModi03** [comment]
@suresh480  Can you please share your code ?? I want to integrate firebase authentication in my xamarin.ios project and I am a complete newbie

**Comment by alexsorokoletov** [comment]
@suresh480 @HemilModi03 
This repository is obsolete.
For Google Firebase and Xamarin, please use official nuget packages, do not generate packages through `objc-sharpie`. Xamarin team did that, there is no reason to repeat that work for you.

**Comment by HemilModi03** [comment]
@alexsorokoleyov  I dont find any such firebase plugin for xamarin for phone number verification, if you have please share it with us.

**Comment by HemilModi03** [comment]
@alexsorokoletov I dont find any such firebase plugin for xamarin for phone number verification, if you have please share it with us.
